version: '3'
services:
  api:
    build: .
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mongodb
      - redis
    environment:
      MONGO_URI: mongodb://mongodb:27017
  
  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: hotel_booking
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
  
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always
    command: redis-server --appendonly yes
